# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
default:
  tags:
  - ci.inria.fr

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp index.html app.js style.css public
  artifacts:
    paths:
      - public
  only:
      - master