# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
default:
  tags:
  - ci.inria.fr 
image:
  name: image: ruby:2.6
  entrypoint: [""]

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r * public
  artifacts:
    paths:
      - public
  only:
      - master